### ISSUE TITLE
Elaborate Documentation

### ISSUE THREAD

**Issue by siba2893** [ajanes93/vuetify-snackbar-queue#1]
Hey I like very much this vuetify snackbar queue. Could you please create some documentation for it?

Also is this in active development?

**Comment by ajanes93** [comment]
Hi, thanks for opening this issue.  This component was not in active development.  It will be actively maintained going forwards and I will also be looking at a new version that supports Vuetify 2.*;  Is there anything specific you would like to see in the docs?  I am aware this issue is over 1 year old, so not sure if you are still using this, but do let me know if you are.

**Comment by ajanes93** [comment]
See updated docs https://ajanes93.github.io/vuetify-snackbar-queue/
